name: snapdrop
services:
  snapdrop:
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    image: linuxserver/snapdrop:version-eac78009
    network_mode: bridge
    ports:
      - target: 443
        published: "443"
        protocol: tcp
      - target: 80
        published: "89"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    privileged: false
    container_name: snapdrop
x-vionetaos:
  architectures:
    - amd64
    - arm64
  description:
    en_us: Snapdrop is a Progressive Web App (PWA) that allows you to transfer files between devices in the same network without having to install anything.
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Snapdrop/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Snapdrop/screenshot-1.png
  tagline:
    en_us: Cross-platform file sharing made easy.
  author: self
  category: File Sync
  hostname: ""
  index: /
  port_map: "89"
  scheme: http
  store_app_id: snapdrop
  title:
    en_us: snapdrop
