name: vflow
services:
  vflow:
    image: vioneta/vflow:latest-debian
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    ports:
      - target: 1880
        published: "1880"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    x-vionetaos:
      ports:
        - container: "1880"
          description:
            en_us: ""

      volumes:
        - container: /data
          description:
            en_us: ""
    container_name: vflow
x-vionetaos:
  architectures:
    - amd64
    - arm64
  main: vflow
  author: Vioneta Team
  category: Agriculture
  description:
    en_us: VFlow is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.  It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.

  developer: Vioneta Team
  icon: https://raw.githubusercontent.com/Vioneta/Vioneta-Appstore/main/Apps/VFlow/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-3.png
  tagline:
    en_us: Low-code programming for event-driven applications
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/thumbnail.png
  tips: {}
  title:
    en_us: VFlow
  index: /
  port_map: "1880"
